
pip3 install numpy
pip3 install openpyxl
pip3 install pandas
pip3 install pandas-datareader
pip3 install pandoc
pip3 install pandocfilters
pip3 install imageio
pip3 install ipykernel
pip3 install ipyparallel
pip3 install sklearn
pip3 install ipython
pip3 install ipython-genutils
pip3 install jedi
pip3 install elpy
pip3 install scipy
pip3 install seaborn
pip3 install sympy
pip3 install rtree
pip3 install cython
pip3 install jupyter
pip3 install jupyter-client
pip3 install jupyter-console
pip3 install jupyter-contrib-core
pip3 install jupyter-contrib-nbextensions
pip3 install jupyter-core
pip3 install jupyter-highlight-selected-word
pip3 install jupyter-latex-envs
pip3 install jupyter-nbextensions-configurator
pip3 install appdirs
pip3 install attrs
pip3 install autopep8
pip3 install backcall
pip3 install beautifulsoup4
pip3 install black
pip3 install bleach
pip3 install bs4
pip3 install certifi
pip3 install chardet
pip3 install Click
pip3 install colorama
pip3 install cycler
pip3 install decorator
pip3 install defusedxml
pip3 install entrypoints
pip3 install et-xmlfile
pip3 install flake8
pip3 install future
pip3 install graphviz
pip3 install idna
pip3 install Jinja2
pip3 install jsonschema
pip3 install kaggle
pip3 install kiwisolver
pip3 install lxml
pip3 install MarkupSafe
pip3 install matplotlib
pip3 install mccabe
pip3 install mistune
pip3 install nbconvert
pip3 install nbformat
pip3 install notebook
pip3 install parso
pip3 install pickleshare
pip3 install Pillow
pip3 install plotly
pip3 install pluggy
pip3 install ply
pip3 install prometheus-client
pip3 install prompt-toolkit
pip3 install pycodestyle
pip3 install pyflakes
pip3 install Pygments
pip3 install pyparsing
pip3 install PyQt5
pip3 install PyQt5-sip
pip3 install python-dateutil
pip3 install python-jsonrpc-server
pip3 install python-language-server
pip3 install python-slugify
pip3 install pytz
pip3 install pywinpty
pip3 install PyYAML
pip3 install pyzmq
pip3 install qtconsole
pip3 install requests
pip3 install retrying
pip3 install rope
pip3 install scikit-learn
pip3 install Send2Trash
pip3 install setuptools
pip3 install simplegeneric
pip3 install six
pip3 install terminado
pip3 install testpath
pip3 install text-unidecode
pip3 install toml
pip3 install tornado
pip3 install tqdm
pip3 install traitlets
pip3 install urllib3
pip3 install wcwidth
pip3 install webencodings
pip3 install widgetsnbextension
pip3 install wrapt
pip3 install xlrd
pip3 install xlwt
pip3 install yapf
pip3 install ipywidgets
pip3 install jdcal
